Ajout rôle postgresql
osm-fr/ansible-scripts pull request #77
Opened 2023-07-01 20:14 UTC by jocelynj

2023-07-02 07:04 UTC, anayrat requested changes

2023-07-02 07:04 UTC, anayrat commented on roles/postgresql/tasks/main.yml
> +      - python3-psycopg2
il manque le paquet zstd pour la compression logrotate

2023-07-02 12:08 UTC, jocelynj commented on roles/postgresql/tasks/main.yml
> +      - python3-psycopg2
Bien vu. J'ai aussi ajouté `pg-activity`.

2023-07-04 13:10 UTC, anayrat commented
J'ai rajouté quelques changements par rapport à pg15. Je n'ai pas pu les pusher sur ta pr, voici le diff.
Attention, le role ne supporte pas d'avoir plusieurs instances sur le même serveur. Il y a des paramètres mémoire qui sont calculés pour une instance par serveur.

[pg15.txt](https://github.com/osm-fr/ansible-scripts/files/11949597/pg15.txt)

2023-07-04 16:34 UTC, anayrat commented
Je pense qu'on devrait aussi déplacer l'ajout des sondes munins dans ce role : https://github.com/osm-fr/ansible-scripts/blob/e38df9dad6c56db048e61d6a9bf08b854cc043d9/roles/common/tasks/munin-node.yml#L65

On devrait activer ces plugins:

* postgres_autovacuum
* postgres_bgwriter
* postgres_cache_
* postgres_checkpoints
* postgres_connections_
* postgres_connections_db
* postgres_locks_
* postgres_oldest_prepared_xact_
* postgres_prepared_xacts_
* postgres_querylength_
* postgres_scans_
* postgres_size_
* postgres_transactions_
* postgres_tuples_
* postgres_users
* postgres_xlog

2023-07-09 15:59 UTC, jocelynj commented
Bonne idée pour les plugins munin - on verra après merge de cette branche.

2023-07-09 15:59 UTC, merged